# Generated by Django 4.2 on 2023-04-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='json_obj',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='json_obj',
            field=models.TextField(null=True),
        ),
    ]
